version: "3.4"


x-minecraft: &minecraft
  image: itzg/minecraft-server
  env_file:
    - "common.env"
  tty: true
  stdin_open: true
  restart: unless-stopped


services:
  Avenoobs0: 
    <<: *minecraft
    ports:
      - 25565:25565
    volumes:
      - ./worlds/Avenoobs0:/data

  Avenoobs1:
    <<: *minecraft
    ports:
      - 25566:25566
    environment:
      SEED: "110918009997"
      SERVER_PORT: "25566"
      QUERY_PORT: "25566"
      RCON_PORT: "25576"
    volumes:
      - ./worlds/Avenoobs1:/data
