version: "3.4"


x-minecraft: &minecraft
  image: itzg/minecraft-server
  tty: true
  stdin_open: true
  restart: unless-stopped

x-env: &env
  EULA: "TRUE"
  ENABLE_AUTOPAUSE: "TRUE"
  JVM_DD_OPTS: "disable.watchdog:true"
 

services:
  Avenoobs0: 
    <<: *minecraft
    environment:
      <<: *env
    ports:
      - 25565:25565
    volumes:
      - ./worlds/Avenoobs0:/data

  Avenoobs1:
    <<: *minecraft
    ports:
      - 25566:25566
    environment:
      <<: *env
      SEED: "110918009997"
      SERVER_PORT: "25566"
      QUERY_PORT: "25566"
      RCON_PORT: "25576"
    volumes:
      - ./worlds/Avenoobs1:/data
